#!/bin/bash
[ -z "$BASH_VERSION" ] && exec /bin/bash "$0" "$@"

u=$(id -u)

if [ "${u}" != "0" ] ; then  
	echo "need to be root"
	exit
fi

mysql -u kloxo -p$(cat /usr/local/lxlabs/kloxo/etc/conf/kloxo.pass) kloxo

