#!/bin/bash
[ -z "$BASH_VERSION" ] && exec /bin/bash "$0" "$@"

#    KloxoNext - (re)configure the mail stack and every mail object.
#    Postfix + Dovecot replace qmail-toaster/vpopmail (not packaged for EL9+/Ubuntu).

. /script/counter-start.inc

sh /script/setup-mail
sh /script/fixmail --nolog
sh /script/fixwebmail

. /script/counter-end.inc
