#!/bin/bash
[ -z "$BASH_VERSION" ] && exec /bin/bash "$0" "$@"

#    KloxoNext - make sure the repositories KloxoNext needs are enabled.
#    (EPEL + CRB + Remi on EL, ondrej/php on Ubuntu; no Kloxo rpm repo anymore)

echo ">>> fixrepo <<<"

. /script/os.inc

if os_is_el ; then
	# repos of older Kloxo releases ship conflicting qmail/php/hiawatha builds
	for r in kloxo kloxo-mr kloxo-custom kloxong lxcenter lxlabs ; do
		[ -f "/etc/yum.repos.d/${r}.repo" ] && mv -f "/etc/yum.repos.d/${r}.repo" "/etc/yum.repos.d/${r}.repo.disabled"
	done
fi

os_setup_repos
pkg_clean

. /script/fix-urgent
