#!/bin/bash
[ -z "$BASH_VERSION" ] && exec /bin/bash "$0" "$@"

. /script/counter-start.inc

if [ -f /script/custom.fix.inc ] ; then
	. /script/custom.fix.inc
else
	. /script/fix.inc
fi

. /script/directory
lxphp.exe ../bin/fix/fixwebcache.php $*

. /script/counter-end.inc
