#!/bin/bash
[ -z "$BASH_VERSION" ] && exec /bin/bash "$0" "$@"

. /script/os.inc

pkg_installed httpry || exit 0

systemctl disable --now httpry >/dev/null 2>&1
pkg_remove httpry
rm -f /etc/logrotate.d/httpry
