#!/bin/bash
[ -z "$BASH_VERSION" ] && exec /bin/bash "$0" "$@"

kloxopath='/usr/local/lxlabs/kloxo'
acmepath='/root/.acme.sh'

if [ -f ${acmepath}/acme.sh ] ; then
	${acmepath}/acme.sh --force --renew-all
	sh /script/fixssl
fi