#!/bin/bash
[ -z "$BASH_VERSION" ] && exec /bin/bash "$0" "$@"

#    KloxoNext - install an extra PHP extension for one branch from packages
#    Example: sh /script/phpm-extension-installer php84m memcached

. /script/os.inc
. /script/php-native.inc

if [ "$#" -lt 2 ] ; then
	echo
	echo " ---------------------------------------------------------------------------"
	echo "  format: sh $0 <phpXYm|phpXYs> <extension>"
	echo " ---------------------------------------------------------------------------"
	echo "  Example: 'sh $0 php84m memcached'"
	echo
	exit
fi

base_name="$1"
ext="$2"
xy="${base_name:3:2}"

. /script/counter-start.inc
echo "=== BEGIN '${ext}' install for ${base_name} ==="

pkg="$(_php_pkg_for_ext "${xy}" "${ext}")"

if ! pkg_available "${pkg}" && os_is_el ; then
	pkg="php${xy}-php-pecl-${ext}"
fi

pkg_install "${pkg}"

# copy the new ini file(s) into the Kloxo layout
php_build_compat_layout "${base_name}"

echo "=== END '${ext}' install ==="
. /script/counter-end.inc
