#!/bin/bash
[ -z "$BASH_VERSION" ] && exec /bin/bash "$0" "$@"

#    KloxoNext - install every PHP branch the repositories provide

. /script/os.inc
. /script/php-native.inc

if [ "$1" == "--help" ] ; then
	sh /script/phpm-installer --help
	exit
fi

os_setup_repos

for xy in $(php_available_branches) ; do
	sh /script/phpm-installer "php${xy}m" "$@"
done

php_set_branch "$(php_latest_installed)"
