#!/bin/bash
[ -z "$BASH_VERSION" ] && exec /bin/bash "$0" "$@"

#    KloxoNext - update every installed PHP branch from the package manager
#    and refresh the /opt/phpXY[m|s] layouts.

. /script/os.inc
. /script/php-native.inc

pkgs=""
for d in /opt/php[0-9][0-9][ms] ; do
	[ -d "${d}" ] || continue
	xy="$(basename "${d}" | cut -c4-5)"
	pkgs="${pkgs} $(php_native_packages "${xy}")"
done

if [ -n "${pkgs}" ] ; then
	echo "- Upgrading native PHP packages"
	# shellcheck disable=SC2086
	pkg_upgrade $(echo ${pkgs} | tr ' ' '\n' | sort -u | tr '\n' ' ')
fi

for d in /opt/php[0-9][0-9][ms] ; do
	[ -d "${d}" ] || continue
	b="$(basename "${d}")"
	php_build_compat_layout "${b}"
	[ "${1}" == "-y" ] || [ "${1}" == "--force" ] && sh /script/phpm-config-setup "${b}"
done

# 'php' branch always follows the newest installed version
php_set_branch "$(php_latest_installed)"
