#!/bin/bash
[ -z "$BASH_VERSION" ] && exec /bin/bash "$0" "$@"

if [ "$1" == "--help" ] ; then
	sh /script/phpm-config-setup --help
	exit
fi

for d in /opt/php[0-9][0-9][ms] ; do
	[ -d "${d}" ] || continue
	sh /script/phpm-config-setup "$(basename "${d}")" "$@"
done
