#!/bin/bash
[ -z "$BASH_VERSION" ] && exec /bin/bash "$0" "$@"

#list=(kloxo)

if [ -f /script/custom.restart-list.inc ] ; then
	. /script/custom.restart-list.inc
else
	. /script/restart-list.inc
fi

bpath="/usr/local/lxlabs/kloxo"
spath="${bpath}/file/pages"
tpath="${bpath}/httpdocs/login"

opath="$(dirname $0)"

if [ -f ${bpath}/init/php_active ] ; then
	mv -f ${bpath}/init/php_active ${bpath}/init/kloxo_php_active
fi

ln -sf /usr/sbin/nginx ${bpath}/init/kloxo-nginx
rm -f ${bpath}/init/kloxo-hiawatha
[ -L ${bpath}/init/kloxo-apps-fpm ] || sh /script/set-kloxo-apps-php
ln -sf /opt/$(cat ${bpath}/init/kloxo_php_active)/custom/php-fpm.sh ${bpath}/init/kloxo-phpcgi

# KloxoNext - the legacy C helpers are no longer built here: create-kloxoexe
# deleted cexe/closeallinput first and then failed without gcc/glibc-static

cp -f ${spath}/default_index.php ${tpath}/index.php
cp -f ${spath}/login_inc.php ${tpath}/inc.php
cp -f ${spath}/login_inc2.php ${tpath}/inc2.php

for i in kloxo-web kloxo-php kloxo-apps kloxo-wrap ; do
	chkconfig ${i} on  >/dev/null 2>&1
done

if [ -f ${bpath}/init/kloxo_use_php-cgi ] ; then
	chkconfig kloxo-php off >/dev/null 2>&1
	service kloxo-php stop >/dev/null 2>&1
fi

list=${list_kloxo[*]}

if [ -f /script/custom.restart.inc ] ; then
	. /script/custom.restart.inc
else
	. /script/restart.inc
fi