#!/bin/bash
[ -z "$BASH_VERSION" ] && exec /bin/bash "$0" "$@"

. /script/directory

'cp' /etc/secondary_master.copy.my.cnf /etc/my.cnf

service mysqld restart

'rm' ../etc/running_secondary

/script/upcp
