#!/bin/bash
[ -z "$BASH_VERSION" ] && exec /bin/bash "$0" "$@"

#    KloxoNext - RainLoop is abandoned upstream; SnappyMail is its maintained successor

sh /script/thirdparty-update --install --only=snappymail
sh /script/add-rainloop-domains
