#!/bin/bash
[ -z "$BASH_VERSION" ] && exec /bin/bash "$0" "$@"

if [ "$1" == "" ] ; then
	skin="nexus"
else
	skin="$1"
fi

for i in $(sh /script/simplelist --resource=all_client) ; do
	sh /script/update --class=sp_specialplay --name=client-${i} \
		--subaction=skin --v-specialplay_b_s_skin_name=${skin} --v-specialplay_b_s_skin_color=default
done
