#!/bin/bash
[ -z "$BASH_VERSION" ] && exec /bin/bash "$0" "$@"

echo "- This webmail is no longer maintained upstream and is not supported by KloxoNext."
echo "  Use Roundcube or SnappyMail: sh /script/thirdparty-update --install"
