<?php

/*
 * KloxoNext - Roundcube configuration
 * Generated by /script/thirdparty-update from file/webmail/roundcube/config.inc.php
 * Put local overrides in config/custom.inc.php (kept across updates).
 */

$config = [];

$config['db_dsnw'] = 'mysql://roundcube:__DB_PASS__@localhost/roundcubemail';

// Mail served by the local Postfix/Dovecot of this server
$config['imap_host'] = 'localhost:143';
$config['smtp_host'] = 'tls://localhost:587';
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';
$config['imap_conn_options'] = $config['smtp_conn_options'] = [
	'ssl' => ['verify_peer' => false, 'verify_peer_name' => false],
];

$config['support_url'] = '';
$config['product_name'] = 'Webmail';
$config['des_key'] = '__DES_KEY__';
$config['username_domain_forced'] = false;
$config['login_autocomplete'] = 2;
$config['ip_check'] = true;
$config['session_lifetime'] = 30;

$config['plugins'] = ['archive', 'zipdownload', 'managesieve', 'markasjunk', 'newmail_notifier'];
$config['skin'] = 'elastic';
$config['enable_installer'] = false;

$config['log_driver'] = 'file';
$config['temp_dir'] = __DIR__ . '/../temp/';
$config['log_dir'] = __DIR__ . '/../logs/';

if (file_exists(__DIR__ . '/custom.inc.php')) {
	include __DIR__ . '/custom.inc.php';
}
